AWSTemplateFormatVersion: "2010-09-09"
Description: "Creates a CodeBuild Project"
Parameters:
  ProjectName:
    Description: "Name of the project"
    Type: "String"
    MinLength: 5
  ProjectDescription:
    Description: "Description of the project"
    Type: "String"
    MinLength: 5
  GitRepoUrl:
    Description: "HTTPS URL to the git repository used for building"
    Type: "String"
    MinLength: 10
  GitRepoProvider:
    Description: "The provider of the git repo, defaults to GITHUB"
    Type: "String"
    Default: GITHUB
  ArtifactS3BucketName:
    Description: "The S3 bucket to use for artifacts"
    Type: "String"
  ServiceRoleARN:
    Description: "The provider of the git repo, defaults to GITHUB"
    Type: "String"
Resources:
  CodeBuildProject:
    Type: "AWS::CodeBuild::Project"
    Properties:
      Artifacts:
        Location: !Ref "ArtifactS3BucketName"
        Name: !Sub "${ProjectName}.zip"
        NamespaceType: BUILD_ID
        Packaging: ZIP
        Path: !Ref "ProjectName"
        Type: S3
      Description: !Ref "ProjectDescription"
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: "aws/codebuild/java:openjdk-8"
        Type: LINUX_CONTAINER
      Name: !Ref "ProjectName"
      ServiceRole: !Ref "ServiceRoleARN"
      Source:
        BuildSpec: buildspec.yml
        GitCloneDepth: 1
        InsecureSsl: False
        Location: !Ref "GitRepoUrl"
        Type: !Ref "GitRepoProvider"
      Tags:
        - Key: "auto-delete"
          Value: "no"
      TimeoutInMinutes: 15
