AWSTemplateFormatVersion: "2010-09-09"
Description: "Creates a CodeBuild IAM Role and Policy"
Parameters:
  ArtifactS3BucketName:
    Description: "Name of the S3 bucket to use for publishing artifacts"
    Type: "String"
    MinLength: 5
Outputs:
  CodeBuildRoleARN:
    Value: !GetAtt "CodeBuildRole.Arn"
Resources:
  CodeBuildRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: "Allow"
          Principal:
            Service:
            - "codebuild.amazonaws.com"
          Action: "sts:AssumeRole"
      Path: "/"
  CodeBuildPolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "logs:CreateLogGroup"
              - "logs:CreateLogStream"
              - "logs:PutLogEvents"
            Resource:
              - !Join
                - ":"
                - - "arn:aws:logs"
                  - Ref: AWS::Region
                  - Ref: AWS::AccountId
                  - "log-group:/aws/codebuild/*"
              - !Join
                - ":"
                - - "arn:aws:logs"
                  - Ref: AWS::Region
                  - Ref: AWS::AccountId
                  - "log-group:/aws/codebuild/*:*"
          - Effect: "Allow"
            Action:
              - "s3:PutObject"
              - "s3:GetObject"
              - "s3:GetObjectVersion"
            Resource:
              - !Join
                - "-"
                - - "arn:aws:s3:::codepipeline"
                  - Ref: AWS::Region
                  - "*"
          - Effect: "Allow"
            Action:
              - "ssm:GetParameters"
            Resource:
              - !Join
                - ":"
                - - "arn:aws:ssm"
                  - Ref: AWS::Region
                  - Ref: AWS::AccountId
                  - "parameter/CodeBuild/*"
          - Effect: "Allow"
            Action:
              - "s3:PutObject"
            Resource:
              - !Join
                - ""
                - - "arn:aws:s3:::"
                  - Ref: ArtifactS3BucketName
                  - "/*"
      PolicyName: "CodeBuildPolicy"
      Roles:
        - Ref: "CodeBuildRole"
